apiVersion: meta.dev.upbound.io/v2alpha1
kind: Project
metadata:
  name: crossplane-configuration-gcp-workload-identity
spec:
  dependsOn:
    - provider: xpkg.upbound.io/upbound/provider-family-gcp
      version: ">=v2.2.0"
    - provider: xpkg.upbound.io/crossplane-contrib/provider-kubernetes
      version: ">=v1"
    - function: xpkg.upbound.io/upbound/function-go-templating
      version: ">=v0.11.0"
    - function: xpkg.upbound.io/upbound/function-auto-ready
      version: ">=v0.5.0"
  description: This is where you can describe your project.
  license: MIT License
  maintainer: Livewyer <bowen@livewyer.com>
  readme: |
    This is where you can add a readme for your project.
  repository: xpkg.upbound.io/livewyer-ops/crossplane-configuration-gcp-workload-identity
  source: github.com/livewyer-ops/crossplane-configuration-gcp-workload-identity
