apiVersion: gcp.livewyer.io/v1alpha1
kind: WorkloadIdentity
metadata:
  name: simple-example
  namespace: default
  annotations:
    crossplane.io/composition-resource-name: workloadidentity.gcp.livewyer.io/simple-example
    test-annotation: "true"
  labels:
    test-label: "true"
spec:
  forProvider:
    projectId: provider-testing
    location: us-east1
    roles:
      - roles/dns.admin
      - roles/compute.admin
    additionalProjects:
      - projectId: provider-testing
        roles:
          - roles/container.admin
          - roles/storage.admin
      - projectId: provider-testing
        roles:
          - roles/cloudsql.admin
    serviceAccountName: simple-example
